baseURL = "https://jenbroek.com/"
capitalizeListTitles = false
cleanDestinationDir = true
copyright = '© 2024 <a href="https://github.com/jenbroek" rel="me external nofollow noreferrer">jenbroek</a>'
disableAliases = true
disableKinds = ["rss"]
enableGitInfo = true
languageCode = "en-US"
removePathAccents = true
title = "jenbroek"

[cascade.build]
publishResources = false

[params.site]
	description = "Jens is a software engineer with a passion for keeping it simple, and learning about software design."
	cdnURL = "https://cdn.jenbroek.com/"
	imgSizes = [350, 700, 1400]
[params.pagination]
	slots = 3

[pagination]
disableAliases = true
pagerSize = 4

[taxonomies]
	tag = "tags"

[permalinks.page]
	posts = "/:year/:month/:day/:slugorcontentbasename/"
	photos = "/:year/:month/:day/:slugorcontentbasename/"

[[menus.main]]
	name = '<svg id="avatar" viewBox="0 0 768 768" role="img"><title>Home</title><use href="/avatar.svg#_"/></svg>'
	pageRef = "/"
	weight = 1
[[menus.main]]
	name = '<span aria-hidden="true" role="img">📬</span> Posts'
	pageRef = "/posts"
	weight = 2
[[menus.main]]
	name = '<span aria-hidden="true" role="img">📸</span> Photos'
	pageRef = "/photos"
	weight = 3

[markup]
	goldmark.parser.attribute.block = true
[markup.goldmark.extensions.extras]
	mark.enable = true
[markup.highlight]
	anchorLineNos = true
	guessSyntax = true
	style = "algol"

[mediaTypes]
"text/cloudflare".delimiter = ""

[outputFormats."_redirects"]
baseName = "_redirects"
isPlainText = true
mediaType = "text/cloudflare"
notAlternative = true

[outputFormats."_headers"]
baseName = "_headers"
isPlainText = true
mediaType = "text/cloudflare"
notAlternative = true

[outputs]
home = ["html", "_redirects", "_headers"]
